/**
 * The photographs the site ships, and what may be said about them.
 *
 * GENERATED by scripts/photos/build.py from scripts/photos/manifest.json.
 * Edit the manifest and re-run the builder; do not edit this file.
 *
 * ── The rule these carry ───────────────────────────────────────────────────
 *
 * Every `alt` here describes what is VISIBLE and nothing more. None of them
 * names window film, paint protection film, a ceramic coating or any other
 * service, because the owner has not confirmed which service any individual
 * photograph documents. A caption that guesses is a claim about work that was
 * done for a real customer, and it would be published beside that customer's
 * vehicle. docs/pro-detailing-web/photo-manifest.md records the outstanding
 * confirmations.
 */

export type SitePhoto = {
  id: string;
  /** Visible description only — never a service name. */
  alt: string;
  /** Intrinsic size of the largest derivative, for width/height attributes. */
  width: number;
  height: number;
  /** Widths generated, smallest first, for the srcset. */
  widths: readonly number[];
  /** Short line shown beside the photograph. Also never a service name. */
  caption: string;
  placement: string;
  /**
   * The body style visible in the frame — saloon, SUV, pickup, coupe. A
   * fact about the photograph rather than about the work, so it is safe
   * to filter on while the service labels are still unconfirmed.
   */
  subject: string;
  /**
   * The service this photograph documents, or null. Null everywhere
   * until the owner confirms the set; the gallery hides the service
   * filter entirely rather than inventing one.
   */
  service: string | null;
};

export const sitePhotos = {
  'studio-front-dark-saloon': {
    id: 'studio-front-dark-saloon',
    alt: 'A black Mercedes-Benz saloon parked in profile on the forecourt outside the PRO Detailing unit, roller door open behind it.',
    width: 1600,
    height: 1199,
    widths: [640, 960, 1280, 1600],
    caption: 'Outside the Manassas unit at the end of the day.',
    placement: 'homepage hero',
    subject: 'saloon',
    service: null,
  },
  'polished-suv-front': {
    id: 'polished-suv-front',
    alt: 'A dark grey Mercedes-AMG SUV photographed head-on, its glossy bodywork and chrome-slat grille reflecting an overcast sky.',
    width: 1200,
    height: 674,
    widths: [400, 640, 900, 1200],
    caption: 'Graphite-grey AMG SUV, head-on.',
    placement: 'gallery (wide) + paint protection film page',
    subject: 'suv',
    service: null,
  },
  'foam-covered-saloon': {
    id: 'foam-covered-saloon',
    alt: 'The front of a dark Tesla saloon covered in a thick layer of white foam, parked on a wet street.',
    width: 1200,
    height: 680,
    widths: [400, 640, 900, 1200],
    caption: 'Foam dwelling on a Model 3 front end.',
    placement: 'gallery',
    subject: 'saloon',
    service: null,
  },
  'glossy-black-coupe': {
    id: 'glossy-black-coupe',
    alt: 'A gloss black BMW coupe parked on a mown lawn beside a private driveway under a clear blue sky.',
    width: 1200,
    height: 672,
    widths: [400, 640, 900, 1200],
    caption: 'Gloss black BMW coupe, summer afternoon.',
    placement: 'gallery + ceramic coating page',
    subject: 'coupe',
    service: null,
  },
  'blue-pickup-profile': {
    id: 'blue-pickup-profile',
    alt: 'A metallic blue GMC Sierra Denali crew-cab pickup parked side-on in a sunlit lot.',
    width: 1200,
    height: 675,
    widths: [400, 640, 900, 1200],
    caption: 'Sierra Denali crew cab, full profile.',
    placement: 'gallery',
    subject: 'pickup',
    service: null,
  },
  'grey-suv-profile': {
    id: 'grey-suv-profile',
    alt: 'A dark grey Lexus SUV parked side-on in a sunlit lot, with vans and industrial storage tanks behind it.',
    width: 1200,
    height: 887,
    widths: [400, 640, 900, 1200],
    caption: 'Lexus RX in profile on the lot.',
    placement: 'gallery',
    subject: 'suv',
    service: null,
  },
  'green-saloon-profile': {
    id: 'green-saloon-profile',
    alt: 'A bright lime green Dodge Charger parked side-on across an asphalt lot in evening light.',
    width: 1200,
    height: 672,
    widths: [400, 640, 900, 1200],
    caption: 'Sublime green Charger R/T at the end of the day.',
    placement: 'gallery',
    subject: 'saloon',
    service: null,
  },
  'white-suv-profile': {
    id: 'white-suv-profile',
    alt: 'A white BMW X7 parked in side profile on an open lot, with a treeline and blue sky behind it.',
    width: 1200,
    height: 900,
    widths: [400, 640, 900, 1200],
    caption: "BMW X7, driver's-side profile.",
    placement: 'gallery + window tinting page',
    subject: 'suv',
    service: null,
  },
  'sports-car-in-bay': {
    id: 'sports-car-in-bay',
    alt: 'A light grey Chevrolet Corvette parked nose-first inside the workshop bay with its door and rear hatch raised.',
    width: 900,
    height: 672,
    widths: [400, 640, 900],
    caption: 'In the bay, hatch up.',
    placement: 'gallery',
    subject: 'coupe',
    service: null,
  },
  'white-pickup-forecourt': {
    id: 'white-pickup-forecourt',
    alt: 'A white GMC Sierra crew cab pickup truck parked side-on across an asphalt forecourt outside a light-grey brick unit with an open overhead door, under a blue sky with tall white clouds.',
    width: 1200,
    height: 900,
    widths: [400, 640, 900, 1200],
    caption: 'White pickup on the forecourt.',
    placement: 'gallery',
    subject: 'pickup',
    service: null,
  },
  'white-suv-studio-door': {
    id: 'white-suv-studio-door',
    alt: "A white Lexus GX SUV parked in side profile on the asphalt outside PRO Detailing's white brick studio unit, with the roller shutter door open behind it on a bright summer day.",
    width: 1200,
    height: 900,
    widths: [400, 640, 900, 1200],
    caption: 'White SUV outside the bay door.',
    placement: 'gallery',
    subject: 'suv',
    service: null,
  },
  'grey-offroader-forecourt': {
    id: 'grey-offroader-forecourt',
    alt: 'A charcoal grey Toyota 4Runner SUV with black wheels, all-terrain tires and a roof rack, parked in side profile beside a cream brick building under a bright sky.',
    width: 1200,
    height: 900,
    widths: [400, 640, 900, 1200],
    caption: 'Grey off-roader on the lot.',
    placement: 'gallery',
    subject: 'suv',
    service: null,
  },
  'blue-offroader-forecourt': {
    id: 'blue-offroader-forecourt',
    alt: 'A blue-grey two-door Ford Bronco with a black roof, black wheels and all-terrain tires, parked side-on beside a white brick industrial unit with brown roller doors.',
    width: 1200,
    height: 900,
    widths: [400, 640, 900, 1200],
    caption: 'Blue off-roader beside the unit.',
    placement: 'gallery',
    subject: 'suv',
    service: null,
  },
  'white-crossover-bay': {
    id: 'white-crossover-bay',
    alt: 'A white Tesla crossover parked side-on outside a white brick industrial unit with dark roller doors, one raised open, under a bright blue sky.',
    width: 1200,
    height: 900,
    widths: [400, 640, 900, 1200],
    caption: 'White crossover at the roller door.',
    placement: 'gallery',
    subject: 'suv',
    service: null,
  },
  'green-saloon-front': {
    id: 'green-saloon-front',
    alt: 'A bright lime-green Dodge Charger sedan parked head-on in an asphalt lot, with a white van, trailer and industrial storage tanks behind it under an overcast sky.',
    width: 900,
    height: 675,
    widths: [400, 640, 900],
    caption: 'Sublime green Charger, head-on.',
    placement: 'gallery',
    subject: 'saloon',
    service: null,
  },
  'white-convertible-lot': {
    id: 'white-convertible-lot',
    alt: 'A white Audi convertible with its black fabric roof raised, parked in side profile outside a white brick unit, with a white box truck and silver minivan behind it.',
    width: 1200,
    height: 900,
    widths: [400, 640, 900, 1200],
    caption: 'White convertible, roof up, on the lot.',
    placement: 'gallery',
    subject: 'coupe',
    service: null,
  },
  'silver-coupe-suv-drive': {
    id: 'silver-coupe-suv-drive',
    alt: 'A grey metallic Mercedes-AMG coupe-SUV with black wheels and red brake calipers, parked on a residential driveway beside an open garage, lawn and trees.',
    width: 1200,
    height: 901,
    widths: [400, 640, 900, 1200],
    caption: 'Silver coupe-SUV on a residential driveway.',
    placement: 'gallery',
    subject: 'suv',
    service: null,
  },
  'dark-fastback-drive': {
    id: 'dark-fastback-drive',
    alt: 'A dark grey four-door coupe parked nose-in on a driveway between two suburban houses, seen from above and behind with neighboring siding reflected across its paint.',
    width: 1200,
    height: 909,
    widths: [400, 640, 900, 1200],
    caption: 'Dark fastback coupe, high rear quarter.',
    placement: 'gallery',
    subject: 'saloon',
    service: null,
  },
  'white-ram-pickup-forecourt': {
    id: 'white-ram-pickup-forecourt',
    alt: 'A white RAM 1500 Limited crew-cab pickup parked side-on across an asphalt forecourt, with trees and industrial storage tanks behind it.',
    width: 1200,
    height: 900,
    widths: [400, 640, 900, 1200],
    caption: 'White RAM 1500, side-on on the forecourt.',
    placement: 'gallery',
    subject: 'pickup',
    service: null,
  },
  'silver-escalade-forecourt': {
    id: 'silver-escalade-forecourt',
    alt: 'A silver Cadillac Escalade parked in side profile on the forecourt, with industrial storage tanks and summer trees behind it.',
    width: 1200,
    height: 901,
    widths: [400, 640, 900, 1200],
    caption: 'Silver Escalade on the forecourt.',
    placement: 'gallery',
    subject: 'suv',
    service: null,
  },
  'white-audi-suv-bay-door': {
    id: 'white-audi-suv-bay-door',
    alt: 'A white Audi SQ5 with black wheels parked in side profile outside the PRO Detailing unit, its roller doors closed behind it.',
    width: 1200,
    height: 900,
    widths: [400, 640, 900, 1200],
    caption: 'White Audi SQ5 outside the unit.',
    placement: 'gallery',
    subject: 'suv',
    service: null,
  },
  'blue-coupe-industrial-park': {
    id: 'blue-coupe-industrial-park',
    alt: 'A metallic blue Subaru BRZ coupe parked at an angle on an industrial-park lot under a cloudy sky.',
    width: 1200,
    height: 901,
    widths: [400, 640, 900, 1200],
    caption: 'Blue BRZ on the lot.',
    placement: 'gallery',
    subject: 'coupe',
    service: null,
  },
  'white-jeep-pickup-forecourt': {
    id: 'white-jeep-pickup-forecourt',
    alt: 'A white Jeep Gladiator Willys crew-cab pickup with black wheels and all-terrain tyres, parked side-on across the forecourt.',
    width: 1200,
    height: 795,
    widths: [400, 640, 900, 1200],
    caption: 'Jeep Gladiator Willys, side-on.',
    placement: 'gallery',
    subject: 'pickup',
    service: null,
  },
  'white-crossover-forecourt': {
    id: 'white-crossover-forecourt',
    alt: 'A white Chevrolet Traverse RS parked side-on on wet asphalt, with parked vans and industrial buildings behind it.',
    width: 1200,
    height: 691,
    widths: [400, 640, 900, 1200],
    caption: 'Chevrolet Traverse on a wet morning.',
    placement: 'gallery',
    subject: 'suv',
    service: null,
  },
  'red-saloon-forecourt': {
    id: 'red-saloon-forecourt',
    alt: 'A red Toyota Camry saloon parked side-on beside a grass verge, with white vans and an industrial unit behind it.',
    width: 1200,
    height: 666,
    widths: [400, 640, 900, 1200],
    caption: 'Red Camry beside the verge.',
    placement: 'gallery',
    subject: 'saloon',
    service: null,
  },
  'white-tesla-bay-door': {
    id: 'white-tesla-bay-door',
    alt: 'A white Tesla Model 3 parked in side profile beside the studio’s brick wall, with a stop sign and parked vehicles further down the lot.',
    width: 1200,
    height: 748,
    widths: [400, 640, 900, 1200],
    caption: 'White Model 3 by the bay door.',
    placement: 'gallery',
    subject: 'saloon',
    service: null,
  },
  'black-pickup-forecourt': {
    id: 'black-pickup-forecourt',
    alt: 'A black Chevrolet Silverado 4x4 crew-cab pickup filling the frame in side profile, with trees and storage tanks behind it.',
    width: 1200,
    height: 558,
    widths: [400, 640, 900, 1200],
    caption: 'Black Silverado, side-on.',
    placement: 'gallery',
    subject: 'pickup',
    service: null,
  },
  'red-suv-bay-door': {
    id: 'red-suv-bay-door',
    alt: 'A dark red GMC Acadia AT4 parked in side profile outside the open workshop bay on a clear afternoon.',
    width: 1200,
    height: 777,
    widths: [400, 640, 900, 1200],
    caption: 'GMC Acadia AT4 outside the bay.',
    placement: 'gallery',
    subject: 'suv',
    service: null,
  },
  'grey-coupe-dusk': {
    id: 'grey-coupe-dusk',
    alt: 'A grey BMW M4 coupe parked in side profile on the lot at dusk, its tail lights lit against a deep blue sky.',
    width: 1200,
    height: 793,
    widths: [400, 640, 900, 1200],
    caption: 'BMW M4 on the lot at dusk.',
    placement: 'gallery',
    subject: 'coupe',
    service: null,
  },
  'silver-sports-car-forecourt': {
    id: 'silver-sports-car-forecourt',
    alt: 'A silver-grey Chevrolet Corvette C8 parked in side profile outside the studio unit in low evening light.',
    width: 1200,
    height: 684,
    widths: [400, 640, 900, 1200],
    caption: 'Corvette C8 in the evening light.',
    placement: 'gallery',
    subject: 'coupe',
    service: null,
  },
} as const satisfies Record<string, SitePhoto>;

export type SitePhotoId = keyof typeof sitePhotos;
